services:
  doil_saltmain:
    build:
      context: .
      dockerfile: Dockerfile
    image: doil_saltmain:stable
    container_name: doil_saltmain
    hostname: doil
    domainname: saltmain
    volumes:
      - /usr/local/share/doil/stack/states:/srv/salt/states
      - /usr/local/share/doil/stack/config/master.cnf:/etc/salt/master
    networks:
      saltnet:
        ipv4_address: 172.20.0.254
networks:
  saltnet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
volumes:
    persistent:
