services:
  doil_office:
    build:
      context: .
      target: documentserver-community
    image: onlyoffice/documentserver
    container_name: doil_office
    hostname: office
    labels:
      doil.compose.doilinstance: "true"
    environment:
      - WOPI_ENABLED=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    stop_grace_period: 60s
    volumes:
      - /var/www/onlyoffice/Data
      - /var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts
    networks:
      doil_proxy:
        ipv4_address: 172.24.0.251

networks:
  doil_proxy:
    external: true