version: "3.5"
services:
  doil_postfix:
    build:
      context: .
      dockerfile: Dockerfile
    image: doil_postfix
    container_name: doil_postfix
    hostname: doil
    domainname: postfix
    networks:
      doil_proxy:
        ipv4_address: 172.24.0.253
      salt_saltnet:
    ports:
      - "8081:80"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - type: bind
        source: ./conf/salt-minion.conf
        target: /etc/supervisor/conf.d/salt-minion.conf
      - type: bind
        source: ./conf/minion.cnf
        target: /etc/salt/minion
networks:
  doil_proxy:
    external: true
  salt_saltnet:
    external: true
volumes:
    persistent:
