#!/bin/bash

# check arguments
if [ -z "$1" ]
then
	echo "Set the folderpath"
	exit
fi

# set the config
CWD=$(pwd)
PLUGINPATH="$FOLDERPATH/volumes/plugins"

# create the directories
mkdir "$PLUGINPATH/Services"
mkdir "$PLUGINPATH/Services/Cron"
mkdir "$PLUGINPATH/Services/Cron/CronHook"
mkdir "$PLUGINPATH/Services/Repository"
mkdir "$PLUGINPATH/Services/Repository/RepositoryObject"
mkdir "$PLUGINPATH/Services/UIComponent"
mkdir "$PLUGINPATH/Services/UIComponent/UserInterfaceHook"
mkdir "$PLUGINPATH/Services/EventHandling"
mkdir "$PLUGINPATH/Services/EventHandling/EventHook"
mkdir "$PLUGINPATH/Modules"
mkdir "$PLUGINPATH/Modules/OrgUnit"
mkdir "$PLUGINPATH/Modules/OrgUnit/OrgUnitTypeHook"

# Clone the repos to their directories
git clone git@github.com:conceptsandtraining/ilias-plugin-CSN "$PLUGINPATH/Services/Repository/RepositoryObject/CSN"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseSubscriptionMails "$PLUGINPATH/Services/EventHandling/EventHook/CourseSubscriptionMails"
git clone git@github.com:conceptsandtraining/ilias-plugin-BareContentView "$PLUGINPATH/Services/UIComponent/UserInterfaceHook/BareContentView"
git clone git@github.com:conceptsandtraining/ilias-plugin-ExitedUserCleanup "$PLUGINPATH/Services/Cron/CronHook/ExitedUserCleanup"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingProvider "$PLUGINPATH/Services/Cron/CronHook/TrainingProvider"
git clone git@github.com:conceptsandtraining/ilias-plugin-ILIASSoapSSO "$PLUGINPATH/Services/Repository/RepositoryObject/ILIASSoapSSO"
git clone git@github.com:conceptsandtraining/ilias-plugin-AutomaticUserAdministration "$PLUGINPATH/Services/Cron/CronHook/AutomaticUserAdministration"
git clone git@github.com:conceptsandtraining/ilias-plugin-UserDataValidationPrompt "$PLUGINPATH/Services/UIComponent/UserInterfaceHook/UserDataValidationPrompt"
git clone git@github.com:conceptsandtraining/ilias-plugin-DeskRedirect "$PLUGINPATH/Services/UIComponent/UserInterfaceHook/DeskRedirect"
git clone git@github.com:conceptsandtraining/ilias-plugin-LoginPage "$PLUGINPATH/Services/UIComponent/UserInterfaceHook/LoginPage"
git clone git@github.com:conceptsandtraining/ilias-plugin-SendCertificatesAsEMailCron "$PLUGINPATH/Services/Cron/CronHook/SendCertificatesAsEMailCron"
git clone git@github.com:conceptsandtraining/ilias-plugin-Accounting "$PLUGINPATH/Services/Repository/RepositoryObject/Accounting"
git clone git@github.com:conceptsandtraining/ilias-plugin-EnhancedLPReport "$PLUGINPATH/Services/Repository/RepositoryObject/EnhancedLPReport"
git clone git@github.com:conceptsandtraining/ilias-plugin-MaterialList "$PLUGINPATH/Services/Repository/RepositoryObject/MaterialList"
git clone git@github.com:conceptsandtraining/ilias-plugin-Venues "$PLUGINPATH/Services/Cron/CronHook/Venues"
git clone git@github.com:conceptsandtraining/ilias-plugin-RoomSetup "$PLUGINPATH/Services/Repository/RepositoryObject/RoomSetup"
git clone git@github.com:conceptsandtraining/ilias-plugin-SkinUpdate "$PLUGINPATH/Services/EventHandling/EventHook/SkinUpdate"
git clone git@github.com:conceptsandtraining/ilias-plugin-TalentAssessment "$PLUGINPATH/Services/Repository/RepositoryObject/TalentAssessment"
git clone git@github.com:conceptsandtraining/ilias-plugin-CareerGoal "$PLUGINPATH/Services/Repository/RepositoryObject/CareerGoal"
git clone git@github.com:conceptsandtraining/ilias-plugin-TalentAssessmentReport "$PLUGINPATH/Services/Repository/RepositoryObject/TalentAssessmentReport"
git clone git@github.com:conceptsandtraining/ilias-plugin-UserAgreementEditor "$PLUGINPATH/Services/Cron/CronHook/UserAgreementEditor"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseClassification "$PLUGINPATH/Services/Repository/RepositoryObject/CourseClassification"
git clone git@github.com:conceptsandtraining/ilias-plugin-StudyProgrammeAutoAssignment "$PLUGINPATH/Services/EventHandling/EventHook/StudyProgrammeAutoAssignment"
git clone git@github.com:conceptsandtraining/ilias-plugin-BookingModalities "$PLUGINPATH/Services/Repository/RepositoryObject/BookingModalities"
git clone git@github.com:conceptsandtraining/ilias-plugin-Webinar "$PLUGINPATH/Services/Repository/RepositoryObject/Webinar"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseClassificationEventHook "$PLUGINPATH/Services/EventHandling/EventHook/CourseClassificationEventHook"
git clone git@github.com:conceptsandtraining/ilias-plugin-Accomodation "$PLUGINPATH/Services/Repository/RepositoryObject/Accomodation"
git clone git@github.com:conceptsandtraining/ilias-plugin-CopySettings "$PLUGINPATH/Services/Repository/RepositoryObject/CopySettings"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseMailing "$PLUGINPATH/Services/Repository/RepositoryObject/CourseMailing"
git clone git@github.com:conceptsandtraining/ilias-plugin-Cockpit "$PLUGINPATH/Services/UIComponent/UserInterfaceHook/Cockpit"
git clone git@github.com:conceptsandtraining/ilias-plugin-UserBookings "$PLUGINPATH/Services/Repository/RepositoryObject/UserBookings"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseMember "$PLUGINPATH/Services/Repository/RepositoryObject/CourseMember"
git clone git@github.com:conceptsandtraining/ilias-plugin-ScaledFeedback "$PLUGINPATH/Services/Repository/RepositoryObject/ScaledFeedback"
git clone git@github.com:conceptsandtraining/ilias-plugin-UserCourseHistorizing "$PLUGINPATH/Services/Cron/CronHook/UserCourseHistorizing"
git clone git@github.com:conceptsandtraining/ilias-plugin-EduBiography "$PLUGINPATH/Services/Repository/RepositoryObject/EduBiography"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingAssignments "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingAssignments"
git clone git@github.com:conceptsandtraining/ilias-plugin-ScheduledEvents "$PLUGINPATH/Services/Cron/CronHook/ScheduledEvents"
git clone git@github.com:conceptsandtraining/ilias-plugin-EduTracking "$PLUGINPATH/Services/Repository/RepositoryObject/EduTracking"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingAdminOverview "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingAdminOverview"
git clone git@github.com:conceptsandtraining/ilias-plugin-AgendaItemPool "$PLUGINPATH/Services/Repository/RepositoryObject/AgendaItemPool"
git clone git@github.com:conceptsandtraining/ilias-plugin-CronJobSurveillance "$PLUGINPATH/Services/Cron/CronHook/CronJobSurveillance"
git clone git@github.com:conceptsandtraining/ilias-plugin-Agenda "$PLUGINPATH/Services/Repository/RepositoryObject/Agenda"
git clone git@github.com:conceptsandtraining/ilias-plugin-CourseCreation "$PLUGINPATH/Services/Cron/CronHook/CourseCreation"
git clone git@github.com:conceptsandtraining/ilias-plugin-StatusMails "$PLUGINPATH/Services/Cron/CronHook/StatusMails"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingDemandAdvanced "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingDemandAdvanced"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingDemandRetarded "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingDemandRetarded"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingStatistics "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingStatistics"
git clone git@github.com:conceptsandtraining/ilias-plugin-BookingApprovals "$PLUGINPATH/Services/Repository/RepositoryObject/BookingApprovals"
git clone git@github.com:conceptsandtraining/ilias-plugin-EmployeeBookingOverview "$PLUGINPATH/Services/Repository/RepositoryObject/EmployeeBookingOverview"
git clone git@github.com:conceptsandtraining/ilias-plugin-WBDCrsHistorizing "$PLUGINPATH/Services/Cron/CronHook/WBDCrsHistorizing"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingSearch "$PLUGINPATH/Services/Repository/RepositoryObject/TrainingSearch"
git clone git@github.com:conceptsandtraining/ilias-plugin-BookingAcknowledge "$PLUGINPATH/Services/Repository/RepositoryObject/BookingAcknowledge"
git clone git@github.com:conceptsandtraining/ilias-plugin-OrguByMailDomain "$PLUGINPATH/Services/EventHandling/EventHook/OrguByMailDomain"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainerOperations "$PLUGINPATH/Services/Repository/RepositoryObject/TrainerOperations"
git clone git@github.com:conceptsandtraining/ilias-plugin-SyncExtCalendars "$PLUGINPATH/Services/Cron/CronHook/SyncExtCalendars"
git clone git@github.com:conceptsandtraining/ilias-plugin-AutomaticCancelWaitinglist "$PLUGINPATH/Services/Cron/CronHook/AutomaticCancelWaitinglist"
git clone git@github.com:conceptsandtraining/ilias-plugin-WorkflowReminder "$PLUGINPATH/Services/Cron/CronHook/WorkflowReminder"
git clone git@github.com:conceptsandtraining/ilias-plugin-CancellationFeeReport "$PLUGINPATH/Services/Repository/RepositoryObject/CancellationFeeReport"
git clone git@github.com:conceptsandtraining/ilias-plugin-TrainingStatisticsByOrgUnits "$PLUGINPATH/Modules/OrgUnit/OrgUnitTypeHook/TrainingStatisticsByOrgUnits"
git clone git@github.com:conceptsandtraining/ilias-plugin-WBDCommunicator "$PLUGINPATH/Services/Cron/CronHook/WBDCommunicator"
git clone git@github.com:conceptsandtraining/ilias-plugin-WBDManagement "$PLUGINPATH/Services/Repository/RepositoryObject/WBDManagement"
git clone git@github.com:conceptsandtraining/ilias-plugin-WBDReport "$PLUGINPATH/Services/Repository/RepositoryObject/WBDReport"
git clone git@github.com:conceptsandtraining/ilias-plugin-ParticipationsImport "$PLUGINPATH/Services/Cron/CronHook/ParticipationsImport"
