name: checks
on: [pull_request, push]
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, zip
          tools: composer:v2
          coverage: none

      - name: Composer install
        run: composer install -d ./app --no-interaction --no-progress

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Python Dependencies
        run: pip install yamllint

      - name: Install doil
        run: sudo ./setup/install.sh
        env:
          GHRUN: yes

      - name: PHP Unit Test
        run: CI/PHPUnit/run_tests.sh
        env:
          GHRUN: "yes"

      - name: Setup Unit Tests
        run: ./setup/tests/tstfy.sh setup/tests/tests

      - name: SLS Tests
        run: ./CI/validate-sls-files.sh setup/stack/states