name: checks
on: [pull_request, push]
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doil
        run: sudo ./install.sh

      - name: Unit Tests
        run: ./tests/tstfy.sh tests